### ISSUE TITLE
Fix Menu on Mobile

### ISSUE THREAD

**Issue by fallsimply** [SimplyCodin/fallproject.github.io#4]
![](https://i.imgur.com/Y5O5rFh.png)
To Test - Set body BG color to not white
``` css
/*MobileMenu*/ {
min-height: 100%
}
```
